name: pg_management
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  provider: ^6.1.2
  material: ^1.0.0+2
  image_picker: ^1.1.1
  firebase_storage: ^11.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/logoPG.png
    - assets/images/neha.jpg
    - assets/images/owner.jpg
    - assets/images/pgIN.jpg
    - assets/images/menu.jpg
    - assets/images/camera.png
    - assets/images/hand.png
  uses-material-design: true
